baseURL = "https://hugo-moo-theme.moo.media/"
languageCode = "en"
title = "moo-theme"
theme = "hugo-moo-theme"

[params]
  subtitle = "theme docs"
  description = "A warm, book-inspired documentation theme for Hugo"
  repoUrl = "https://github.com/jackbhickey/hugo-moo-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
